#!/bin/bash
set -e

source $(dirname $0)/version

cd $(dirname $0)/..

IMAGE=${REPO}/harvester-lvm-provisioner:${TAG}
DOCKERFILE=package/Dockerfile.provisioner
if [ -e ${DOCKERFILE}.${ARCH} ]; then
    DOCKERFILE=${DOCKERFILE}.${ARCH}
fi

if docker buildx version >/dev/null 2>&1; then
    docker buildx build --platform linux/${ARCH} --load -f ${DOCKERFILE} -t ${IMAGE} .
else
    docker build -f ${DOCKERFILE} -t ${IMAGE} .
fi
echo Built ${IMAGE}
