name: Dev Build and Publish

on:
  push:
    branches:
      - main

jobs:
  build-for-dev:
    uses: ./.github/workflows/factory.yml
    permissions:
      contents: read
      id-token: write
    with:
      tag: ${{ github.ref_name }}-head
      push: true
    secrets: inherit
